name: Scheduled Model Retraining

permissions:
  contents: write

on:
  schedule:
    - cron: "0 3 * * 0" # Weekly, Sunday 3AM UTC
  workflow_dispatch: # Manual trigger (important)

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download dataset
        run: |
          mkdir -p data
          curl -L "https://transaction-fuck.s3.us-east-1.amazonaws.com/PS_20174392719_1491204439457_log.csv?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQCV7uZCFj46RQw82C%2FxLrMRtIvBd%2BJGJkg8UAiUg56X2gIhAJWRDgoj32aO2ma%2FTuNxoxM%2FZSlJ6oM0HfNpyjkMS1r6KsIDCKz%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMMDI3MzU0MzIyMjA1Igz5FzvFKI6uiH5OEmwqlgPk5Ox%2FgCyK4CBGLinf5ho1bYtbgJbJJ4UNGVwQ0DctGLxKeZuz96qJHe8ht3l7hXjv%2Ft6Yne9ymsEN%2BTbcP2kw6cmU72fWY6BZCqm4CcvIJTessbWl%2F1DDqDGj1o1CjoQt0o5sPmr1l05P1i%2BufpVdPEGOKZ7C2fA%2BfTXVsxzxpHCRQMDtL%2BSrAlsLmdWg8PV3HPl%2FVdV9yza7fD1xeANzeTCfa4AV7gyvi9gaGfZiGIGx8RVeGJRsIdPUFp8XVadws3fWyYTgXhabdwMfhtJJgBEqjLEgN8Eqmus4LXt2nwULRP5Tc7%2BEfAw9L8S7kaUcH2HAvpV97F62G%2BMysiQCsojcdCIkzgmR%2FI%2B0pNHg2QZk%2Fvh7xHc5NYIgT4%2B5zpduluKEsX%2B9P11bmKUDz%2F2%2BL7HcZmxljnbH%2BFXP2l1hdmCjTINZNuttLgc1fG13IB77D1A5MDuLBOvXunWPjdOIP4XP6FmypLljIPYQ5DJYzRKfzGnPSUQDYBTeCYdPx49MZ3Y1QgKxqh08qGGnzLl6gkkyaOkBMJPihMsGOt0CiAriBDgW8jsgrkeh6WuwdOYqTrFPfA3Vu%2FPCxoYIqqeHb8Jy4u5wcUidHof3f%2BHCn1VkAUPctV0vQpNj2fMQQuqDscCxQnPtyxaJB13i5jCPxBM%2Fux2BBtoyaTPARoIaJ0JxIHKkbLojTIUmWZdKjwtwpLqLoY25GBXfgxjGAUaAc%2Bshw5kZg3xMzr56F14ScRXJF7xh7aTalEjQoCrCKb7i5bekN%2BE1%2B88vLmiM0t90T0LP6aV5sqVRJvOi6%2F9azLnplXBQXNr0pspeRmnOztQTI%2Be9Lkcru%2BXbhNnU%2F3RZS%2FHSG3oU4Id2ZlgekPFfaggxcEhitoJQeNaCDOwlTds5%2BOEaCWwdAoMPAw6eO3KD5isw%2BjX5YU8UCkZCe%2FlMio0SevuHvTKIaYYjxs0rHP07Nf%2FRmIW5UtmDlp8dvs8CvZ2Hwiy2FLtDIO3oa6ia%2FIqEW99G%2BnEvXAXWpQ%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQMXTR2UO5ZT2O5F6%2F20260109%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260109T184322Z&X-Amz-Expires=39600&X-Amz-SignedHeaders=host&X-Amz-Signature=e814f4f821008aea68306ecc1caf55891d89b62c9b01601cf850aa03ea5f447f" -o data/transactions.csv

      - name: Run retraining pipeline
        id: retrain
        run: |
          python training/retraining.py
        continue-on-error: true

      - name: Commit promoted model
        if: steps.retrain.outcome == 'success'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add training/models/
          git commit -m "Auto-promote model via retraining pipeline"
          git push

        # - name: Reload model in FastAPI
        #   if: steps.retrain.outcome == 'success'
        #   run: |
        #     curl -X POST "$ML_RELOAD_URL" \
        #          -H "Authorization: Bearer $ML_RELOAD_TOKEN"
        env:
          ML_RELOAD_URL: ${{ secrets.ML_RELOAD_URL }}
          ML_RELOAD_TOKEN: ${{ secrets.ML_RELOAD_TOKEN }}
